### ISSUE TITLE
Projects are using old .net version.

### ISSUE THREAD

**Issue by RdebSono** [Azure-Samples/ms-identity-docs-code-dotnet#90]
Some projects are using .net 6, can we have a version with .net 8?

A sample of blazor 8 with both server and webassembly calling an API (fast API ;)) would be nice.

**Comment by AbdulGafoor-inmar** [comment]
TargetFramework: net8.0
You can place this in your .csproj files, upgrade your nuget packages and use the best practices whatever you need in that. And check the functionality.
Tell me more about your problem which you are facing?

**Comment by OwenRichards1** [comment]
Thanks for the feedback @RdebSono & @AbdulGafoor-inmar - these samples have now been updated to the latest versions of .NET.
